import os

# ---------------------------------------------------------
# INPUT PATHS
# ---------------------------------------------------------
# Ground truth dataset from Member 1
DATASET_PATH = "data/samples/kaggle_dataset_v2.json"

# Prediction text logs generated by Member 2
RESULTS_DIR = "results"
STRATEGY_FILES = {
    "zero_shot": os.path.join(RESULTS_DIR, "zeroshot_gemini.txt"),
    "few_shot": os.path.join(RESULTS_DIR, "fewshot_gemini.txt"),
    "chain_of_thought": os.path.join(RESULTS_DIR, "cot_gemini.txt")
}

# ---------------------------------------------------------
# OUTPUT PATHS
# ---------------------------------------------------------
OUTPUT_REPORT_PATH = "eval/results_summary.json"
MISCLASSIFICATIONS_DIR = "eval/misclassifications"
PLOTS_DIR = "eval/plots"

# ---------------------------------------------------------
# EVALUATION SETTINGS
# ---------------------------------------------------------
# Hypothetical enterprise pricing used for cost-tradeoff projections
PRICING = {
    "input_per_1k": 0.00015,
    "output_per_1k": 0.00060
}