import os

# ---------------------------------------------------------
# INPUT PATHS
# ---------------------------------------------------------
# Ground truth dataset from Member 1
DATASET_PATH = "Final_2/poc/data/samples/kaggle_dataset_v2.json"

# Prediction text logs generated by Member 2 (Local Windows Path)
LOCAL_LOG_DIR = "Final_2/member2/result"

STRATEGY_FILES = {
    "zero_shot": os.path.join(LOCAL_LOG_DIR, "zeroshot_gemini.txt"),
    "few_shot": os.path.join(LOCAL_LOG_DIR, "fewshot_gemini.txt"),
    "chain_of_thought": os.path.join(LOCAL_LOG_DIR, "cot_gemini.txt")
}

# ---------------------------------------------------------
# OUTPUT PATHS
# ---------------------------------------------------------
# Dynamically lock the output directory to the location of this config file
BASE_DIR = os.path.dirname(os.path.abspath(__file__))
EVAL_DIR = os.path.join(BASE_DIR, "eval")

OUTPUT_REPORT_PATH = os.path.join(EVAL_DIR, "results_summary.json")
MISCLASSIFICATIONS_DIR = os.path.join(EVAL_DIR, "misclassifications")
PLOTS_DIR = os.path.join(EVAL_DIR, "plots")

# ---------------------------------------------------------
# EVALUATION SETTINGS
# ---------------------------------------------------------
# Hypothetical enterprise pricing used for cost-tradeoff projections
PRICING = {
    "input_per_1k": 0.00015,
    "output_per_1k": 0.00060
}